requires 'Array::Utils';
requires 'XML::XPath';
requires 'XML::XPath::Node';
requires 'Math::Random::MT::Auto';
requires 'XML::LibXML';
requires 'XML::XPathScript';
requires 'Pod::Manual';
requires 'Class::XSAccessor' , '1.18';
requires 'Time::Duration::Parse';
requires 'Date::Parse';
requires 'Data::Transpose', 0.0008;
requires 'DBD::mysql';
requires 'DBI';
requires 'DBIx::Class';
requires 'DBIx::Class::EncodedColumn';
requires 'DBIx::Class::TimeStamp';
requires 'DBIx::Class::Schema::Loader';
requires 'Dancer::Plugin::DBIC';
requires 'Dancer::Plugin::Email';
requires 'Dancer::Plugin::Auth::Extensible';
requires 'Dancer::Plugin::Auth::Extensible::Provider::DBIC';
requires 'Dancer';
requires 'Dancer::Session::Storable';
requires 'DBIx::Class::Tree::AdjacencyList';
requires 'Dancer::Plugin::Interchange6', 0.010;
#requires 'Dancer::Session::DBIC';
requires 'Dancer::Template::TemplateFlute', '0.0106';
requires 'Interchange6::Schema', '0.018';
requires 'Interchange6', '0.011';
requires 'Template::Flute', '0.0107';
requires 'Facebook::Graph';
requires 'Scalar::MoreUtils';
requires 'String::Random';
requires 'Number::Format';
requires 'DateTime';
requires 'DateTime::Locale';
requires 'Business::OnlinePayment';
requires 'Business::OnlinePayment::Braintree';
requires 'Moo';
requires 'MooX::Types::MooseLike';
requires 'WebService::Solr';
requires 'Math::Pari';
requires 'Net::SSLeay';
requires 'AnyEvent::TLS';
requires 'Plack';
requires 'Plack::Handler::Starman';
requires 'XML::Twig', '3.46';
requires 'YAML::Syck';
