requires 'File::Path';
requires 'File::Spec';
requires 'HTTP::Tiny';
requires 'Imager';
requires 'Cache::FileCache';
requires 'HTML::Obliterate';
requires 'Set::Tiny';
requires 'DateTime::Format::ISO8601';
requires 'Net::Easypost';
requires 'URL::Encode';
requires 'Dancer::Debug';
requires 'Plack::Middleware::Debug';
requires 'Plack::Middleware::DBIC::QueryLog';
requires 'Plack::Middleware::Debug::DBIC::QueryLog';
requires 'Plack::Middleware::Debug::Dancer::TemplateVariables';
requires 'Acme::MetaSyntactic';
requires 'Class::Load';
requires 'DBIx::Class::Helpers';
requires 'Template';
requires 'DBIx::Class::Tree::NestedSet';
requires 'Pod::POM';
requires 'Test::CheckManifest';
requires 'Module::Path';
requires 'Test::mysqld';
requires 'DateTime::Format::Pg';
requires 'Plack::App::URLMap';
requires 'Dancer::Plugin::Database';
requires 'Faker';
requires 'Acme::MetaSyntactic::Themes';
requires 'Data::Faker';
requires 'Data::Faker::MetaSyntactic';
requires 'Data::Generate';
requires 'Getopt::Long';
requires 'Term::ReadLine';
requires 'Tie::IxHash';
requires 'Term::UI';
requires 'Test::MockTime';
requires 'DBIx::Class::Helper::ResultSet::Random';
requires 'DBIx::Class::Result::Validation';
requires 'Data::Generate';
requires 'Hash::Merge::Simple';
requires 'Time::ParseDate';
requires 'Time::Format';
requires 'DateTime::Tiny';
requires 'Term::ProgressBar';
requires 'Array::Utils';
requires 'XML::XPath';
requires 'XML::XPath::Node';
requires 'Math::Random::MT::Auto';
requires 'XML::LibXML';
requires 'XML::XPathScript';
requires 'Pod::Manual';
requires 'Class::XSAccessor' , '1.18';
requires 'Time::Duration::Parse';
requires 'Date::Parse';
requires 'Data::Transpose', 0.0009;
requires 'DBD::mysql';
requires 'DBI';
requires 'DBIx::Class';
requires 'DBIx::Class::EncodedColumn';
requires 'DBIx::Class::TimeStamp';
requires 'DBIx::Class::Schema::Loader';
requires 'Dancer::Plugin::DBIC';
requires 'Dancer::Plugin::Email';
requires 'Dancer::Plugin::Auth::Extensible';
requires 'Dancer::Plugin::Auth::Extensible::Provider::DBIC';
requires 'Dancer';
requires 'Dancer::Session::Storable';
requires 'DBIx::Class::Tree::AdjacencyList';
# requires 'Dancer::Plugin::Interchange6', '0.040';
requires 'Dancer::Session::DBIC';
# requires 'Dancer::Template::TemplateFlute', '0.0113';
# requires 'Interchange6::Schema', '0.050';
requires 'Interchange6', '0.063';
# requires 'Template::Flute', '0.0113';
requires 'Facebook::Graph';
requires 'Scalar::MoreUtils';
requires 'String::Random';
requires 'Number::Format';
requires 'DateTime';
requires 'DateTime::Locale';
requires 'Business::OnlinePayment';
requires 'Business::OnlinePayment::Braintree';
requires 'Moo';
requires 'MooX::Types::MooseLike';
requires 'MooX::Singleton';
requires 'WebService::Solr';
requires 'Net::SSLeay';
#requires 'AnyEvent::TLS';
requires 'Plack';
requires 'Plack::Handler::Starman';
requires 'XML::Twig', '3.46';
requires 'YAML::Syck';
requires 'XSLoader';
requires 'XML::Simple';
requires 'Data::UUID';
requires 'XML::RSS';
requires 'Date::Calc';
requires 'Business::PayPal::API', 0.70;
requires 'File::MimeInfo';
requires 'Net::Easypost', '0.13';
