<?php /* Smarty version 2.6.10, created on 2006-05-24 17:22:32
         compiled from gallery:themes/PGtheme/templates/navigatorAlbumBottom.tpl */ ?>

<?php if (empty ( $this->_tpl_vars['theme']['params']['colorpack'] )): ?>
  <table border="0" width="99%">
    <tr>
      <td width="33%">
        <?php echo '';  if (isset ( $this->_tpl_vars['theme']['navigator']['first'] ) || isset ( $this->_tpl_vars['theme']['navigator']['back'] )):  echo '';  if (isset ( $this->_tpl_vars['theme']['navigator']['first'] )):  echo '<a href="';  echo $this->_reg_objects['g'][0]->url(array('params' => $this->_tpl_vars['theme']['navigator']['first']['urlParams']), $this); echo '" onmouseover="firstpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'themes/PGtheme/images/'), $this); echo 'firston.gif\'" onmouseout="firstpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'themes/PGtheme/images/'), $this); echo 'first.gif\'" title="first"><img name="firstpicB" src="';  echo $this->_reg_objects['g'][0]->url(array('href' => 'themes/PGtheme/images/'), $this); echo 'first.gif" border="0" alt="first" title="first" longdesc="first" id="firstpicB" class="navpic"/></a>';  endif;  echo '';  if (isset ( $this->_tpl_vars['theme']['navigator']['back'] )):  echo '<a href="';  echo $this->_reg_objects['g'][0]->url(array('params' => $this->_tpl_vars['theme']['navigator']['back']['urlParams']), $this); echo '" onmouseover="prevpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'themes/PGtheme/images/'), $this); echo 'prevon.gif\'" onmouseout="prevpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'themes/PGtheme/images/'), $this); echo 'prev.gif\'" title="previous"><img name="prevpicB" src="';  echo $this->_reg_objects['g'][0]->url(array('href' => 'themes/PGtheme/images/'), $this); echo 'prev.gif" border="0" alt="previous" title="previous" longdesc="previous" id="prevpicB" class="navpic"/></a>';  endif;  echo '';  endif;  echo ''; ?>

      </td>
      <td width="33%" style="text-align:center">
        <?php echo '';  if (! empty ( $this->_tpl_vars['theme']['jumpRange'] )):  echo '<div id="gsPagesB">';  echo $this->_reg_objects['g'][0]->text(array('text' => "<font class='giInfo'>Page:</font>"), $this); echo '';  $this->assign('lastPage', 0);  echo '';  $_from = $this->_tpl_vars['theme']['jumpRange']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }$this->_foreach['jumpRange'] = array('total' => count($_from), 'iteration' => 0);
if ($this->_foreach['jumpRange']['total'] > 0):
    foreach ($_from as $this->_tpl_vars['page']):
        $this->_foreach['jumpRange']['iteration']++;
 echo '';  if (( $this->_tpl_vars['page'] - $this->_tpl_vars['lastPage'] >= 2 )):  echo '<span>';  if (( $this->_tpl_vars['page'] - $this->_tpl_vars['lastPage'] == 2 )):  echo '<a href="';  echo $this->_reg_objects['g'][0]->url(array('arg1' => "view=core:ShowItem",'arg2' => "itemId=".($this->_tpl_vars['theme']['item']['id']),'arg3' => "page=".($this->_tpl_vars['page']-1)), $this); echo '">';  echo $this->_tpl_vars['page']-1;  echo '</a>';  else:  echo '...';  endif;  echo '</span>';  endif;  echo '<span>&nbsp;';  if (( $this->_tpl_vars['theme']['currentPage'] == $this->_tpl_vars['page'] )):  echo '<font class=\'giInfo\'>';  echo $this->_tpl_vars['page'];  echo '</font>';  else:  echo '<a href="';  echo $this->_reg_objects['g'][0]->url(array('arg1' => "view=core:ShowItem",'arg2' => "itemId=".($this->_tpl_vars['theme']['item']['id']),'arg3' => "page=".($this->_tpl_vars['page'])), $this); echo '">';  echo $this->_tpl_vars['page'];  echo '</a>';  endif;  echo '</span>';  $this->assign('lastPage', $this->_tpl_vars['page']);  echo '';  endforeach; endif; unset($_from);  echo '</div>';  endif;  echo ''; ?>

      </td>
      <td width="33%" style="text-align:right">
        <?php echo '';  if (isset ( $this->_tpl_vars['theme']['navigator']['next'] ) || isset ( $this->_tpl_vars['theme']['navigator']['last'] )):  echo '';  if (isset ( $this->_tpl_vars['theme']['navigator']['next'] )):  echo '<a href="';  echo $this->_reg_objects['g'][0]->url(array('params' => $this->_tpl_vars['theme']['navigator']['next']['urlParams']), $this); echo '" onmouseover="nextpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'themes/PGtheme/images/'), $this); echo 'nexton.gif\'" onmouseout="nextpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'themes/PGtheme/images/'), $this); echo 'next.gif\'" title="next"><img name="nextpicB" src="';  echo $this->_reg_objects['g'][0]->url(array('href' => 'themes/PGtheme/images/'), $this); echo 'next.gif" border="0" alt="next" title="next" longdesc="next" id="nextpicB" class="navpic"/></a>';  endif;  echo '';  if (isset ( $this->_tpl_vars['theme']['navigator']['last'] )):  echo '<a href="';  echo $this->_reg_objects['g'][0]->url(array('params' => $this->_tpl_vars['theme']['navigator']['last']['urlParams']), $this); echo '" onmouseover="lastpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'themes/PGtheme/images/'), $this); echo 'laston.gif\'" onmouseout="lastpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'themes/PGtheme/images/'), $this); echo 'last.gif\'" title="last"><img name="lastpicB" src="';  echo $this->_reg_objects['g'][0]->url(array('href' => 'themes/PGtheme/images/'), $this); echo 'last.gif" border="0" alt="last" title="last" longdesc="last" id="lastpicB" class="navpic"/></a>';  endif;  echo '';  endif;  echo ''; ?>

      </td>
    </tr>
  </table>
<?php else: ?>
  <table border="0" width="100%">
    <tr>
      <td width="33%">
        <?php echo '';  if (isset ( $this->_tpl_vars['theme']['navigator']['first'] ) || isset ( $this->_tpl_vars['theme']['navigator']['back'] )):  echo '';  if (isset ( $this->_tpl_vars['theme']['navigator']['first'] )):  echo '<a href="';  echo $this->_reg_objects['g'][0]->url(array('params' => $this->_tpl_vars['theme']['navigator']['first']['urlParams']), $this); echo '" onmouseover="firstpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'modules/colorpack/packs/'), $this); echo '';  echo $this->_tpl_vars['theme']['params']['colorpack'];  echo '/images/firston.gif\'" onmouseout="firstpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'modules/colorpack/packs/'), $this); echo '';  echo $this->_tpl_vars['theme']['params']['colorpack'];  echo '/images/first.gif\'" title="first"><img name="firstpicB" src="';  echo $this->_reg_objects['g'][0]->url(array('href' => 'modules/colorpack/packs/'), $this); echo '';  echo $this->_tpl_vars['theme']['params']['colorpack'];  echo '/images/first.gif" border="0" alt="first" title="first" longdesc="first" id="firstpicB" class="navpic"/></a>';  endif;  echo '';  if (isset ( $this->_tpl_vars['theme']['navigator']['back'] )):  echo '<a href="';  echo $this->_reg_objects['g'][0]->url(array('params' => $this->_tpl_vars['theme']['navigator']['back']['urlParams']), $this); echo '" onmouseover="prevpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'modules/colorpack/packs/'), $this); echo '';  echo $this->_tpl_vars['theme']['params']['colorpack'];  echo '/images/prevon.gif\'" onmouseout="prevpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'modules/colorpack/packs/'), $this); echo '';  echo $this->_tpl_vars['theme']['params']['colorpack'];  echo '/images/prev.gif\'" title="previous"><img name="prevpicB" src="';  echo $this->_reg_objects['g'][0]->url(array('href' => 'modules/colorpack/packs/'), $this); echo '';  echo $this->_tpl_vars['theme']['params']['colorpack'];  echo '/images/prev.gif" border="0" alt="previous" title="previous" longdesc="previous" id="prevpicB" class="navpic"/></a>';  endif;  echo '';  endif;  echo ''; ?>

      </td>
      <td width="33%" style="text-align:center">
        <?php echo '';  if (! empty ( $this->_tpl_vars['theme']['jumpRange'] )):  echo '<div id="gsPagesB">';  echo $this->_reg_objects['g'][0]->text(array('text' => "<font class='giInfo'>Page:</font>"), $this); echo '';  $this->assign('lastPage', 0);  echo '';  $_from = $this->_tpl_vars['theme']['jumpRange']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }$this->_foreach['jumpRange'] = array('total' => count($_from), 'iteration' => 0);
if ($this->_foreach['jumpRange']['total'] > 0):
    foreach ($_from as $this->_tpl_vars['page']):
        $this->_foreach['jumpRange']['iteration']++;
 echo '';  if (( $this->_tpl_vars['page'] - $this->_tpl_vars['lastPage'] >= 2 )):  echo '<span>';  if (( $this->_tpl_vars['page'] - $this->_tpl_vars['lastPage'] == 2 )):  echo '<a href="';  echo $this->_reg_objects['g'][0]->url(array('arg1' => "view=core:ShowItem",'arg2' => "itemId=".($this->_tpl_vars['theme']['item']['id']),'arg3' => "page=".($this->_tpl_vars['page']-1)), $this); echo '">';  echo $this->_tpl_vars['page']-1;  echo '</a>';  else:  echo '...';  endif;  echo '</span>';  endif;  echo '<span>&nbsp;';  if (( $this->_tpl_vars['theme']['currentPage'] == $this->_tpl_vars['page'] )):  echo '<font class=\'giInfo\'>';  echo $this->_tpl_vars['page'];  echo '</font>';  else:  echo '<a href="';  echo $this->_reg_objects['g'][0]->url(array('arg1' => "view=core:ShowItem",'arg2' => "itemId=".($this->_tpl_vars['theme']['item']['id']),'arg3' => "page=".($this->_tpl_vars['page'])), $this); echo '">';  echo $this->_tpl_vars['page'];  echo '</a>';  endif;  echo '</span>';  $this->assign('lastPage', $this->_tpl_vars['page']);  echo '';  endforeach; endif; unset($_from);  echo '</div>';  endif;  echo ''; ?>

      </td>
      <td width="33%" style="text-align:right">
        <?php echo '';  if (isset ( $this->_tpl_vars['theme']['navigator']['next'] ) || isset ( $this->_tpl_vars['theme']['navigator']['last'] )):  echo '';  if (isset ( $this->_tpl_vars['theme']['navigator']['next'] )):  echo '<a href="';  echo $this->_reg_objects['g'][0]->url(array('params' => $this->_tpl_vars['theme']['navigator']['next']['urlParams']), $this); echo '" onmouseover="nextpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'modules/colorpack/packs/'), $this); echo '';  echo $this->_tpl_vars['theme']['params']['colorpack'];  echo '/images/nexton.gif\'" onmouseout="nextpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'modules/colorpack/packs/'), $this); echo '';  echo $this->_tpl_vars['theme']['params']['colorpack'];  echo '/images/next.gif\'" title="next"><img name="nextpicB" src="';  echo $this->_reg_objects['g'][0]->url(array('href' => 'modules/colorpack/packs/'), $this); echo '';  echo $this->_tpl_vars['theme']['params']['colorpack'];  echo '/images/next.gif" border="0" alt="next" title="next" longdesc="next" id="nextpicB" class="navpic"/></a>';  endif;  echo '';  if (isset ( $this->_tpl_vars['theme']['navigator']['last'] )):  echo '<a href="';  echo $this->_reg_objects['g'][0]->url(array('params' => $this->_tpl_vars['theme']['navigator']['last']['urlParams']), $this); echo '" onmouseover="lastpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'modules/colorpack/packs/'), $this); echo '';  echo $this->_tpl_vars['theme']['params']['colorpack'];  echo '/images/laston.gif\'" onmouseout="lastpicB.src=\'';  echo $this->_reg_objects['g'][0]->url(array('href' => 'modules/colorpack/packs/'), $this); echo '';  echo $this->_tpl_vars['theme']['params']['colorpack'];  echo '/images/last.gif\'" title="last"><img name="lastpicB" src="';  echo $this->_reg_objects['g'][0]->url(array('href' => 'modules/colorpack/packs/'), $this); echo '';  echo $this->_tpl_vars['theme']['params']['colorpack'];  echo '/images/last.gif" border="0" alt="last" title="last" longdesc="last" id="lastpicB" class="navpic"/></a>';  endif;  echo '';  endif;  echo ''; ?>

      </td>
    </tr>
  </table>
<?php endif; ?>