# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Angler"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_flute"

# session engine
session: "DBIC"
session_expires: "16 hours"

# template: "template_toolkit"
# engines:
#   template_toolkit:
#     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

# log to a file by default
logger: file

# use better log format than default
logger_format: "%t [%P] %L @%D> %m in %f l. %l"

behind_proxy: "true"

records:
  # number of products shown in left sidebar of the flypage
  other_products: 4

free_shipping: 
  amount: 100

plugins:
  Interchange6::Routes:
    product:
      template: flypage
    checkout:
      template: cart_checkout
    navigation:
      records: 20
      template: product-listing
    cart:
      template: cart
  Auth::Extensible:
    disable_roles: 0
    no_login_handler: 1
    login_page: /login
    logout_page: /logout
    denied_page: /login/denied
    no_default_pages: 1
    no_api_change_warning: 1
    realms:
      users:
        provider: 'DBIC'
        db_connection_name: 'default'
        users_resultset: User
        roles_relationship: roles
        role_column: name
        username_column: username
        password_column: password
        password_check: check_password
  Email:
    transport:
      Sendmail:
