# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Angler"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "/main/content"

appdir: "/home/sam/camp10/applications/Angler"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_flute"

# session engine
session: "DBIC"
session_expires: "16 hours"

# plack
plack_middlewares:
  -
    - Debug
    - panels
    -
      - DBIC::QueryLog
      - Memory

# template: "template_toolkit"
# engines:
#   template_toolkit:
#     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

engines:
  template_flute:
    filters:
      currency:
        options:
          int_curr_symbol: "$"
      rating_class:
        class: "DanceShop::Filters::RatingClass"
      selling_price:
        class: "DanceShop::Filters::SellingPrice"
        options:
          int_curr_symbol: "$"

# log to a file by default
logger: file

# use better log format than default
logger_format: "%t [%P] %L @%D> %m in %f l. %l"

behind_proxy: "true"

records:
  # number of products shown in left sidebar of the flypage
  other_products: 4

free_shipping: 
  amount: 100

flypage:
  related_product:
    qty: 3

order_email: orders@westbranchangler.com

plugins:
  Interchange6::Routes:
    product:
      template: flypage/content
    checkout:
      template: checkout/content
    navigation:
      records: 9 
      template: product/grid/content
    cart:
      template: cart/content
  Auth::Extensible:
    disable_roles: 0
    no_login_handler: 1
    login_page: /login
    logout_page: /logout
    denied_page: /login/denied
    no_default_pages: 1
    no_api_change_warning: 1
    realms:
      users:
        provider: 'DBIC'
        db_connection_name: 'default'
        users_resultset: User
        roles_relationship: roles
        role_column: name
        username_column: username
        password_column: password
        password_check: check_password
  Email:
    transport:
      Sendmail:

importer:
    options:
        product_prefix: WB
        join_string: "-"
        filters:
            Attribute:
                name:
                    - lc
                    - special2underscore
            AttributeValue:
                value:
                    - lc
                    - special2underscore
            Navigation:
                uri:
                    - lc
                    - special2underscore
                    - space2dash
            Product:
                sku:
                    - lc
                    - space2dash
                uri:
                    - lc
                    - special2underscore
                    - space2dash
    manufacturers:
        hatch:
            prefix: HA
            full_name: Hatch Outdoors
            short_name: Hatch
        loomis:
            prefix: LO
            full_name: Loomis
        orvis:
            prefix: OR
            full_name: The Orvis Company
            short_name: Orvis
            type: xml
            fields:
                description:
                    - xml:PF_Description|Best_Item_Name|PF_Name
                price:
                    - xml:Min_List_Price|Min_Regular_Price
                name:
                    - short_name
                    - xml:Best_Item_Name|PF_Name
                navigation:
                    - xml:Dir_Name
                    - xml:Group_Name
                    - xml:Cat_Name
                    - xml:SubCat_Name
                sku:
                    - product_prefix
                    - prefix
                    - xml:PF_ID
                uri:
                    - short_name
                    - xml:Best_Item_Name|PF_Name
                canonical:
                    sku:
                        - product_prefix
                        - prefix
        patagonia:
            prefix: PA
            full_name: Patagonia
            type: xls
            fields:
                navigation:
                    - xls:Category1
                    - xls:Category2
                    - xls:Category3
                all:
                    price: xls:Retail
                    gtin: UPC
                canonical:
                    sku:
                        - product_prefix
                        - prefix
                        - xls:Item
                    name:
                        - full_name
                        - xls:Product
                    uri:
                        - full_name
                        - xls:Product
                variant:
                    attributes:
                        color: xls:Color
                        size: xls:Size
                    sku:
                        - product_prefix
                        - prefix
                        - xls:Item
                        - xls:Color_Code
                        - xls:Size
                    name:
                        - full_name
                        - xls:Product
                        - xls:Color_Code
                    uri:
                        - full_name
                        - xls:Product
                        - xls:Color_Code
                        - xls:Size
            navigation_alias:
                filters:
                    -
                        field: Product
                        regexp: "^M's"
                        result: men
                    -
                        field: Product
                        regexp: "^W's"
                        result: women
                clothing:
                    - men:
                        - outerwear:
                            - alpine/shell-tops
                            - alpine/shell-bottoms
                            - alpine/insulation-tops
                            - trail-running/tops
                            - trail-running/bottoms
                            - trail-running/outerwear
                    - women:
                        - outerwear:
                            - alpine/shell-tops
                            - alpine/shell-bottoms
                            - alpine/insulation-tops
                            - trail-running/tops
                            - trail-running/bottoms
                            - trail-running/outerwear
                    - kids:
        sage:
            prefix: SA
            full_name: Sage
        scott:
            prefix: SC
            full_name: Scott
        simms:
            prefix: SI
            full_name: Simms Fishing Products
            short_name: Simms
